export type CryptoMarket = {
  id: string;
  name?: string;
  symbol: string;
  image?: string;
  price_idr: string;
  change_percent: string;
  isPositive: boolean;
  hot: boolean;
  isFavorite: boolean;
  type: 'cryptocurrency';
};

export const cryptoMarketsFallback: CryptoMarket[] = [
  {
    id: 'bitcoin',
    name: 'Bitcoin',
    symbol: 'BITC',
    image: 'https://assets.coingecko.com/coins/images/1/large/bitcoin.png',
    price_idr: 'IDR 1.125.031.726,00',
    change_percent: '+2,51%',
    isPositive: true,
    hot: true,
    isFavorite: true,
    type: 'cryptocurrency',
  },
  {
    id: 'ethereum',
    name: 'Ethereum',
    symbol: 'ETHE',
    image: 'https://assets.coingecko.com/coins/images/279/large/ethereum.png',
    price_idr: 'IDR 29.506.891,00',
    change_percent: '+4,48%',
    isPositive: true,
    hot: true,
    isFavorite: true,
    type: 'cryptocurrency',
  },
  {
    id: 'tether',
    symbol: 'TETH',
    price_idr: 'IDR 18.087,68',
    change_percent: '+0,01%',
    isPositive: true,
    hot: false,
    isFavorite: true,
    type: 'cryptocurrency',
  },
  {
    id: 'binancecoin',
    symbol: 'BINA',
    price_idr: 'IDR 10.774.936,00',
    change_percent: '+3,79%',
    isPositive: true,
    hot: true,
    isFavorite: true,
    type: 'cryptocurrency',
  },
  {
    id: 'solana',
    symbol: 'SOLA',
    price_idr: 'IDR 1.180.688,00',
    change_percent: '+5,30%',
    isPositive: true,
    hot: false,
    isFavorite: true,
    type: 'cryptocurrency',
  },
  {
    id: 'ripple',
    name: 'Ripple',
    symbol: 'RIPP',
    image: 'https://assets.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png',
    price_idr: 'IDR 20.619,00',
    change_percent: '+4,19%',
    isPositive: true,
    hot: false,
    isFavorite: true,
    type: 'cryptocurrency',
  },
  {
    id: 'usd-coin',
    symbol: 'USD-',
    price_idr: 'IDR 18.090,40',
    change_percent: '-0,00%',
    isPositive: false,
    hot: false,
    isFavorite: true,
    type: 'cryptocurrency',
  },
  {
    id: 'cardano',
    name: 'Cardano',
    symbol: 'CARD',
    price_idr: 'IDR 2.944,44',
    change_percent: '+2,15%',
    isPositive: true,
    hot: true,
    isFavorite: true,
    type: 'cryptocurrency',
  },
  {
    id: 'dogecoin',
    name: 'Dogecoin',
    symbol: 'DOGE',
    price_idr: 'IDR 1.536,62',
    change_percent: '+4,72%',
    isPositive: true,
    hot: true,
    isFavorite: true,
    type: 'cryptocurrency',
  },
  {
    id: 'tron',
    name: 'Tron',
    symbol: 'TRON',
    price_idr: 'IDR 5.916,17',
    change_percent: '+1,61%',
    isPositive: true,
    hot: true,
    isFavorite: true,
    type: 'cryptocurrency',
  },
  {
    id: 'polkadot',
    name: 'Polkadot',
    symbol: 'POLK',
    price_idr: 'IDR 17.558,23',
    change_percent: '+3,31%',
    isPositive: true,
    hot: true,
    isFavorite: true,
    type: 'cryptocurrency',
  },
  {
    id: 'litecoin',
    name: 'Litecoin',
    symbol: 'LITE',
    price_idr: 'IDR 758.186,00',
    change_percent: '+0,04%',
    isPositive: true,
    hot: true,
    isFavorite: true,
    type: 'cryptocurrency',
  },
  {
    id: 'chainlink',
    name: 'Chainlink',
    symbol: 'CHAI',
    price_idr: 'IDR 140.191,00',
    change_percent: '+5,28%',
    isPositive: true,
    hot: true,
    isFavorite: true,
    type: 'cryptocurrency',
  },
  {
    id: 'avalanche-2',
    name: 'Avalanche-2',
    symbol: 'AVAL',
    price_idr: 'IDR 121.164,00',
    change_percent: '+0,27%',
    isPositive: true,
    hot: false,
    isFavorite: true,
    type: 'cryptocurrency',
  },
  {
    id: 'uniswap',
    name: 'Uniswap',
    symbol: 'UNIS',
    price_idr: 'IDR 45.753,00',
    change_percent: '+3,51%',
    isPositive: true,
    hot: true,
    isFavorite: true,
    type: 'cryptocurrency',
  },
  {
    id: 'cosmos',
    name: 'Cosmos',
    symbol: 'COSM',
    price_idr: 'IDR 30.490,00',
    change_percent: '+3,82%',
    isPositive: true,
    hot: true,
    isFavorite: true,
    type: 'cryptocurrency',
  },
  {
    id: 'stellar',
    name: 'Stellar',
    symbol: 'STEL',
    price_idr: 'IDR 3.753,86',
    change_percent: '-1,97%',
    isPositive: false,
    hot: false,
    isFavorite: true,
    type: 'cryptocurrency',
  },
  {
    id: 'monero',
    name: 'Monero',
    symbol: 'MONE',
    price_idr: 'IDR 5.677.027,00',
    change_percent: '+3,82%',
    isPositive: true,
    hot: true,
    isFavorite: true,
    type: 'cryptocurrency',
  },
  {
    id: 'okb',
    name: 'Okb',
    symbol: 'OKB',
    price_idr: 'IDR 1.291.454,00',
    change_percent: '+3,49%',
    isPositive: true,
    hot: true,
    isFavorite: true,
    type: 'cryptocurrency',
  },
  {
    id: 'near',
    name: 'Near',
    symbol: 'NEAR',
    price_idr: 'IDR 37.047,00',
    change_percent: '+8,68%',
    isPositive: true,
    hot: true,
    isFavorite: true,
    type: 'cryptocurrency',
  },
  {
    id: 'aptos',
    name: 'Aptos',
    symbol: 'APTO',
    price_idr: 'IDR 12.129,40',
    change_percent: '+2,88%',
    isPositive: true,
    hot: false,
    isFavorite: true,
    type: 'cryptocurrency',
  },
  {
    id: 'arbitrum',
    name: 'Arbitrum',
    symbol: 'ARBI',
    price_idr: 'IDR 1.481,54',
    change_percent: '+2,93%',
    isPositive: true,
    hot: false,
    isFavorite: true,
    type: 'cryptocurrency',
  },
  {
    id: 'optimism',
    name: 'Optimism',
    symbol: 'OPTI',
    price_idr: 'IDR 1.727,73',
    change_percent: '+1,20%',
    isPositive: true,
    hot: false,
    isFavorite: true,
    type: 'cryptocurrency',
  },
  {
    id: 'filecoin',
    name: 'Filecoin',
    symbol: 'FILE',
    price_idr: 'IDR 13.789,14',
    change_percent: '+5,21%',
    isPositive: true,
    hot: false,
    isFavorite: true,
    type: 'cryptocurrency',
  },
  {
    id: 'internet-computer',
    name: 'Internet-Computer',
    symbol: 'INTE',
    price_idr: 'IDR 42.700,00',
    change_percent: '+2,88%',
    isPositive: true,
    hot: false,
    isFavorite: true,
    type: 'cryptocurrency',
  },
  {
    id: 'hedera-hashgraph',
    name: 'Hedera-Hashgraph',
    symbol: 'HEDE',
    price_idr: 'IDR 1.470,32',
    change_percent: '+2,61%',
    isPositive: true,
    hot: true,
    isFavorite: true,
    type: 'cryptocurrency',
  },
  {
    id: 'vechain',
    name: 'Vechain',
    symbol: 'VECH',
    price_idr: 'IDR 87,42',
    change_percent: '+2,67%',
    isPositive: true,
    hot: false,
    isFavorite: true,
    type: 'cryptocurrency',
  },
  {
    id: 'theta-token',
    name: 'Theta-Token',
    symbol: 'THET',
    price_idr: 'IDR 2.756,00',
    change_percent: '+2,01%',
    isPositive: true,
    hot: false,
    isFavorite: true,
    type: 'cryptocurrency',
  },
  {
    id: 'the-sandbox',
    name: 'The-Sandbox',
    symbol: 'THE-',
    price_idr: 'IDR 949,25',
    change_percent: '+1,36%',
    isPositive: true,
    hot: true,
    isFavorite: true,
    type: 'cryptocurrency',
  },
  {
    id: 'aave',
    name: 'Aave',
    symbol: 'AAVE',
    price_idr: 'IDR 1.140.446,00',
    change_percent: '+4,08%',
    isPositive: true,
    hot: false,
    isFavorite: true,
    type: 'cryptocurrency',
  },
  {
    id: 'maker',
    name: 'Maker',
    symbol: 'MAKE',
    price_idr: 'IDR 24.185.382,00',
    change_percent: '+2,75%',
    isPositive: true,
    hot: false,
    isFavorite: true,
    type: 'cryptocurrency',
  },
];
